name: Meta-Llama-3-8B-Instruct
parameters:
  # Model file name
  model: huggingface://QuantFactory/Meta-Llama-3-8B-Instruct-GGUF/Meta-Llama-3-8B-Instruct.Q6_K.gguf
  top_p: 80
  top_k: 0.9
  temperature: 0.9

stopwords:
- "<|eot_id|>"
- "<|end_of_text|>"
