name: qwen2-7b-instruct
parameters:
  # Model file name
  model: huggingface://Qwen/Qwen2-7B-Instruct-GGUF/qwen2-7b-instruct-q6_k.gguf
  top_p: 80
  top_k: 0.9
  temperature: 0.9

stopwords:
- "<|im_end|>"
